from typing import Any

# Type alias used for opaque Python capsules returned by the C extension.
Capsule = Any

# constants
F_BLACK: int
F_RED: int
F_GREEN: int
F_YELLOW: int
F_BLUE: int
F_MAGENTA: int
F_CYAN: int
F_WHITE: int

B_BLACK: int
B_RED: int
B_GREEN: int
B_YELLOW: int
B_BLUE: int
B_MAGENTA: int
B_CYAN: int
B_WHITE: int

A_RESET: int
A_BRIGHT: int
A_FAINT: int
A_ITALIC: int
A_UNDERLINE: int
A_BLINK: int
A_BLINK_FAST: int
A_REVERSE: int
A_HIDDEN: int
A_STRIKETHROUGH: int

DIRECTION_UP: int
DIRECTION_DOWN: int
DIRECTION_RIGHT: int
DIRECTION_LEFT: int
BEGINNING_OF_NEXT_LINE: int
BEGINNING_OF_PREVIOUS_LINE: int

def set_foreground_color(color: int) -> None: ...
def set_background_color(color: int) -> None: ...
def set_attribute(attribute: int) -> None: ...
def reset_attribute(attribute: int) -> None: ...
def reset_ansi() -> None: ...
def print(message: str) -> None: ...

def create_swappable_field(width: int, height: int) -> Capsule: ...
def create_ansi_settings(fgcolor: int = ..., bgcolor: int = ..., attribute: int = ...) -> Capsule: ...
def create_border(symbol: str, ansi_settings: Capsule) -> Capsule: ...
def create_pawn_in_swappable_field(field: Capsule, symbol: str, ansi_settings: Capsule, coords: Capsule) -> Capsule: ...
def create_coordinates(y: int, x: int) -> Capsule: ...
def move_pawn(field: Capsule, pawn: Capsule, dx: int, dy: int) -> int: ...
def add_pawn_to_swap(field: Capsule, pawn: Capsule, coords: Capsule) -> int: ...
def create_pawn_in_field(field: Capsule, symbol: str, ansi_settings: Capsule, coords: Capsule) -> Capsule: ...
def print_swappable_field_with_border(field: Capsule, border: Capsule) -> None: ...
def print_field_with_border(field: Capsule, border: Capsule) -> None: ...
def create_cursor() -> Capsule: ...
def move_cursor(cursor: Capsule, direction: int, amount: int) -> None: ...
def cursor_go_to(cursor: Capsule, y: int, x: int) -> None: ...
def cursor_go_to_coordinates(cursor: Capsule, coords: Capsule) -> None: ...
