on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    # expose the step output as a job output
    outputs:
      artifacts: ${{ steps.build_debs.outputs.artifacts }}
    steps:
      - uses: actions/checkout@v4
      - id: build_debs
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          source-dir: packageroot
          buildpackage-opts: --build=binary --no-sign

  upload-artifacts:
    needs: build-debs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        name: Debian packages
        with:
          path: ${{ needs.build-debs.outputs.artifacts }}
          name: debian-packages
          if-no-files-found: warn
