on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          source-dir: packageroot
          buildpackage-opts: --build=binary --no-sign
  upload-artifacts:
    needs: build-debs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        name: Upload Debian packages
        with:
          path: ${{ steps.build-debs.outputs.artifacts }}
          name: debian-packages
