on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          source-dir: packageroot
          buildpackage-opts: --build=binary --no-sign
    # The previous one outputs as "artifacts" the paths to the .deb files it built.
    # We want to upload them as workflow artifacts.
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build-debs.outputs.artifacts }}
          name: debian-packages
