name: Makefile CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Makefile'
      - 'include/**'
      - '*.cpp'
      - '*.hpp'
      - '.github/workflows/makefile.yml'
  pull_request:
    branches:
        - main
        - '**'

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make
      
      - name: Run demo tests
        run: |
          cd demo
          make all
      
      - name: Display test results
        run: |
          echo "Running demo tests"
          # Find all executables that don't have "shared" in their name
          find demo/ -type f -executable ! -name '*shared*' ! -name 'Makefile' -exec {} \;

  linux:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make
      
      - name: Run demo tests
        run: |
          cd demo
          make all
      
      - name: Display test results
        run: |
          echo "Running demo tests"
          # Find all executables that don't have "shared" in their name
          find demo/ -type f -executable ! -name '*shared*' ! -name 'Makefile' -exec {} \;

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make
      
      - name: Run demo tests
        run: |
          cd demo
          make all
      
      - name: Display test results
        run: |
          echo "Running demo tests"
          # Find all executables that don't have "shared" in their name
          find demo/ -type f -perm +111 ! -name '*shared*' ! -name 'Makefile' -exec {} \;
